apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wpc12vflt-nodejs 
  janus-idp.io/tekton: wpc12vflt-nodejs
  backstage.io/kubernetes-id: wpc12vflt-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wpc12vflt-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml