apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wpc12vflt-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wpc12vflt-nodejs 
  name: wpc12vflt-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wpc12vflt-nodejs 
